/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foreign_trade;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author super
 */


public class choose extends javax.swing.JFrame {

    /**
     * Creates new form choose
     */
    String username2;
    public choose() {
        initComponents();
    }
    public choose(String username1) {
        initComponents();
        this.username2=username1;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tradePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tradePU").createEntityManager();
        goods_1Query = java.beans.Beans.isDesignTime() ? null : tradePUEntityManager.createQuery("SELECT g FROM Goods_1 g");
        goods_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : goods_1Query.getResultList();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        goods_1Query1 = java.beans.Beans.isDesignTime() ? null : tradePUEntityManager.createQuery("SELECT g FROM Goods_1 g");
        goods_1List1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : goods_1Query1.getResultList();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("trade?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        goods_1Query2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT g FROM Goods_1 g");
        goods_1List2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : goods_1Query2.getResultList();
        goods_1Query3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT g FROM Goods_1 g");
        goods_1List3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : goods_1Query3.getResultList();
        confirmedOrdersQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM ConfirmedOrders c");
        confirmedOrdersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : confirmedOrdersQuery.getResultList();
        goods_1Query4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT g FROM Goods_1 g");
        goods_1List4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : goods_1Query4.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        show = new javax.swing.JButton();
        expno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose required goods for trade");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, goods_1List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${goodName}"));
        columnBinding.setColumnName("Good Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${exportingCountry}"));
        columnBinding.setColumnName("Exporting Country");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantity}"));
        columnBinding.setColumnName("Quantity");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${exportingNo}"));
        columnBinding.setColumnName("Exporting No");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        expno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expnoActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Exporting No: ");

        jLabel3.setText("Enter quantity:");

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(show)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirm)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qty, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(expno))))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(show)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(confirm)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
String country1;
String good_name1;
String qty1;
String price1;


String expno1;

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/trade?zeroDateTimeBehavior=convertToNull","root","");
            String selectQuery="select * from goods";
            Statement stat=con.createStatement();
            ResultSet rs=stat.executeQuery(selectQuery);
            //country1=rs.getString("exporting_country");
           // good_name1=rs.getString("good_name");
            
            jTable1.setModel(Dbutils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);           
            
            
            
        }
        catch(Exception e){
            System.out.println(e);            
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_showActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        expno1=expno.getText();
        qty1=qty.getText();         
                
                
                
                
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trade?zeroDateTimeBehavior=convertToNull","root","");
            String qty_temp=qty1;
            String selectQuery="select * from goods where exporting_no='"+expno1+"'";
            Statement stat=con.createStatement();
            ResultSet rs=stat.executeQuery(selectQuery);
            if(rs.next()){
            country1=rs.getString("exporting_country");
            good_name1=rs.getString("good_name");
            System.out.println(country1);
            }
            
            
            
            String insertQuery="insert into confirmed_orders values('"+good_name1+"','"+country1+"',"+qty1+",'"+expno1+"','"+username2+"')";
            Statement st=con.createStatement();
            int x=st.executeUpdate(insertQuery);
            System.out.print(x);
            
            String updateQuery="update goods set quantity=quantity-"+qty1+" where exporting_no='"+expno1+"'";
            Statement st1=con.createStatement();
            int y=st1.executeUpdate(updateQuery);
            System.out.print(y);
            
            String selectQuery2="select * from goods where exporting_no='"+expno1+"'";
            Statement stat2=con.createStatement();
            ResultSet rs2=stat.executeQuery(selectQuery2);
            if(rs2.next()){
            country1=rs2.getString("exporting_country");
            good_name1=rs2.getString("good_name");
            price1=rs2.getString("unit_price");
            
                
               
            
            }
            
            
           
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
        
        
                
                
           dispose();
           Bill up = new Bill();
           up.setLocationRelativeTo(null);
           up.setVisible(true);      
        
        
        
        
        
        
        
    }//GEN-LAST:event_confirmActionPerformed

    private void expnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private java.util.List<foreign_trade.ConfirmedOrders> confirmedOrdersList;
    private javax.persistence.Query confirmedOrdersQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField expno;
    private java.util.List<foreign_trade.Goods_1> goods_1List;
    private java.util.List<foreign_trade.Goods_1> goods_1List1;
    private java.util.List<foreign_trade.Goods_1> goods_1List2;
    private java.util.List<foreign_trade.Goods_1> goods_1List3;
    private java.util.List<foreign_trade.Goods_1> goods_1List4;
    private javax.persistence.Query goods_1Query;
    private javax.persistence.Query goods_1Query1;
    private javax.persistence.Query goods_1Query2;
    private javax.persistence.Query goods_1Query3;
    private javax.persistence.Query goods_1Query4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField qty;
    private javax.swing.JButton show;
    private javax.persistence.EntityManager tradePUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
